export default [
  'appusers',
  'interfacestandards',
  'bworksparameters',
  'bworksstandards',
  'measuremethods',
  'dataloggers',
  'meters',
  'sensors',
  'sensorprobes',
  'bworkssources',
  'pumps',
  'bworkssourcegroups',
  'srcconfigs',
];
